-- Blindagem do app mobile e dashboard de Subprodutos.
-- Execute depois de schema.sql, dashboard_subprodutos_rpc.sql e mobile_subproduct_bridge.sql.
-- Seguro para reexecutar. Nao apaga coletas existentes.

begin;

create extension if not exists pgcrypto;

alter table public.headcount_colaboradores
  add column if not exists senha_hash text;

update public.headcount_colaboradores
set senha_hash = case
  when coalesce(senha_hash, '') <> '' then senha_hash
  when coalesce(senha, '') like '$2%' then senha
  else crypt(coalesce(nullif(senha, ''), '1234'), gen_salt('bf', 10))
end
where coalesce(senha_hash, '') = '';

alter table public.headcount_colaboradores
  alter column senha drop default,
  alter column senha drop not null;

-- A senha deixa de ser retornavel. O hash fica acessivel apenas dentro das funcoes SECURITY DEFINER.
update public.headcount_colaboradores set senha = null where senha is not null;

create table if not exists public.mobile_sessions (
  token_hash text primary key,
  matricula text not null references public.headcount_colaboradores(matricula) on delete cascade,
  dispositivo_id text,
  criado_em timestamptz not null default now(),
  ultimo_uso_em timestamptz not null default now(),
  expira_em timestamptz not null default (now() + interval '30 days'),
  revogado_em timestamptz
);

create index if not exists mobile_sessions_matricula_idx
  on public.mobile_sessions (matricula, expira_em desc);

create table if not exists public.mobile_login_attempts (
  id bigint generated by default as identity primary key,
  matricula text not null,
  sucesso boolean not null,
  criado_em timestamptz not null default now()
);

create index if not exists mobile_login_attempts_recent_idx
  on public.mobile_login_attempts (matricula, criado_em desc);

create table if not exists public.mobile_audit_log (
  id bigint generated by default as identity primary key,
  matricula text,
  dispositivo_id text,
  acao text not null,
  entidade text,
  entidade_id text,
  detalhes jsonb,
  criado_em timestamptz not null default now()
);

create index if not exists mobile_audit_log_created_idx
  on public.mobile_audit_log (criado_em desc);

create table if not exists public.field_deposit_audit (
  id bigint generated by default as identity primary key,
  field_deposit_id uuid,
  acao text not null,
  actor_label text,
  old_data jsonb,
  new_data jsonb,
  criado_em timestamptz not null default now()
);

create index if not exists field_deposit_audit_deposit_idx
  on public.field_deposit_audit (field_deposit_id, criado_em desc);

alter table public.mobile_sessions enable row level security;
alter table public.mobile_login_attempts enable row level security;
alter table public.mobile_audit_log enable row level security;
alter table public.field_deposit_audit enable row level security;
alter table public.field_deposit_tombstones enable row level security;

create or replace function public.mobile_session_owner(p_session_token text)
returns text
language sql
security definer
stable
set search_path = public, extensions
as $$
  select session.matricula
  from public.mobile_sessions session
  join public.headcount_colaboradores collaborator
    on collaborator.matricula = session.matricula
   and collaborator.status = 'ATIVO'
  where session.token_hash = encode(digest(coalesce(p_session_token, ''), 'sha256'), 'hex')
    and session.revogado_em is null
    and session.expira_em > now()
  limit 1;
$$;

create or replace function public.mobile_authenticate(
  p_matricula text,
  p_senha text,
  p_dispositivo_id text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_matricula text := regexp_replace(coalesce(p_matricula, ''), '[^0-9]', '', 'g');
  v_collaborator public.headcount_colaboradores%rowtype;
  v_token text;
  v_recent_failures integer;
begin
  delete from public.mobile_login_attempts
  where criado_em < now() - interval '30 days';

  delete from public.mobile_sessions
  where expira_em <= now() or revogado_em is not null;

  select count(*)
  into v_recent_failures
  from public.mobile_login_attempts
  where matricula = v_matricula
    and sucesso = false
    and criado_em > now() - interval '15 minutes';

  if v_recent_failures >= 8 then
    raise exception using
      errcode = 'P0001',
      message = 'Muitas tentativas. Aguarde alguns minutos e tente novamente.';
  end if;

  select *
  into v_collaborator
  from public.headcount_colaboradores
  where matricula = v_matricula
    and status = 'ATIVO'
  limit 1;

  if v_collaborator.matricula is null
    or coalesce(v_collaborator.senha_hash, '') = ''
    or crypt(coalesce(p_senha, ''), v_collaborator.senha_hash) <> v_collaborator.senha_hash then
    insert into public.mobile_login_attempts (matricula, sucesso)
    values (coalesce(nullif(v_matricula, ''), 'desconhecida'), false);

    return jsonb_build_object('authenticated', false);
  end if;

  insert into public.mobile_login_attempts (matricula, sucesso)
  values (v_collaborator.matricula, true);

  v_token := encode(gen_random_bytes(32), 'hex');

  insert into public.mobile_sessions (
    token_hash,
    matricula,
    dispositivo_id,
    criado_em,
    ultimo_uso_em,
    expira_em
  ) values (
    encode(digest(v_token, 'sha256'), 'hex'),
    v_collaborator.matricula,
    nullif(trim(coalesce(p_dispositivo_id, '')), ''),
    now(),
    now(),
    now() + interval '30 days'
  );

  insert into public.mobile_usuarios (
    id,
    matricula,
    nome,
    cargo,
    departamento,
    gestor,
    ultimo_login_em,
    updated_at
  ) values (
    v_collaborator.matricula,
    v_collaborator.matricula,
    v_collaborator.nome,
    v_collaborator.cargo,
    v_collaborator.departamento,
    v_collaborator.gestor,
    now(),
    now()
  ) on conflict (id) do update set
    nome = excluded.nome,
    cargo = excluded.cargo,
    departamento = excluded.departamento,
    gestor = excluded.gestor,
    ultimo_login_em = excluded.ultimo_login_em,
    updated_at = excluded.updated_at;

  insert into public.mobile_audit_log (matricula, dispositivo_id, acao, entidade, entidade_id)
  values (v_collaborator.matricula, p_dispositivo_id, 'login', 'mobile_session', v_collaborator.matricula);

  return jsonb_build_object(
    'authenticated', true,
    'session_token', v_token,
    'expires_at', now() + interval '30 days',
    'matricula', v_collaborator.matricula,
    'nome', v_collaborator.nome,
    'departamento', v_collaborator.departamento,
    'cargo', v_collaborator.cargo,
    'gestor', v_collaborator.gestor,
    'status', v_collaborator.status
  );
end;
$$;

create or replace function public.mobile_session_profile(p_session_token text)
returns table (
  matricula text,
  nome text,
  departamento text,
  cargo text,
  gestor text,
  status text,
  expires_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_owner text;
begin
  v_owner := public.mobile_session_owner(p_session_token);
  if v_owner is null then
    return;
  end if;

  update public.mobile_sessions
  set ultimo_uso_em = now()
  where token_hash = encode(digest(coalesce(p_session_token, ''), 'sha256'), 'hex');

  return query
  select
    collaborator.matricula,
    collaborator.nome,
    collaborator.departamento,
    collaborator.cargo,
    collaborator.gestor,
    collaborator.status,
    session.expira_em
  from public.headcount_colaboradores collaborator
  join public.mobile_sessions session on session.matricula = collaborator.matricula
  where collaborator.matricula = v_owner
    and session.token_hash = encode(digest(coalesce(p_session_token, ''), 'sha256'), 'hex')
  limit 1;
end;
$$;

create or replace function public.mobile_logout(p_session_token text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  update public.mobile_sessions
  set revogado_em = now()
  where token_hash = encode(digest(coalesce(p_session_token, ''), 'sha256'), 'hex')
    and revogado_em is null;
  return found;
end;
$$;

create or replace function public.mobile_headcount_directory(
  p_session_token text,
  p_offset integer default 0,
  p_limit integer default 500
)
returns table (
  matricula text,
  nome text,
  departamento text,
  cargo text,
  gestor text,
  status text,
  admissao_excel text,
  fonte_aba text,
  fonte_arquivo text,
  reference_date text,
  imported_at text
)
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if public.mobile_session_owner(p_session_token) is null then
    raise exception using errcode = 'P0001', message = 'Sessao mobile invalida ou expirada.';
  end if;

  return query
  select
    collaborator.matricula,
    collaborator.nome,
    collaborator.departamento,
    collaborator.cargo,
    collaborator.gestor,
    collaborator.status,
    collaborator.admissao_excel,
    collaborator.fonte_aba,
    collaborator.fonte_arquivo,
    collaborator.reference_date,
    collaborator.imported_at
  from public.headcount_colaboradores collaborator
  where collaborator.status = 'ATIVO'
  order by collaborator.matricula
  offset greatest(coalesce(p_offset, 0), 0)
  limit least(greatest(coalesce(p_limit, 500), 1), 1000);
end;
$$;

create or replace function public.mobile_headcount_lookup(
  p_session_token text,
  p_matricula text
)
returns table (
  matricula text,
  nome text,
  departamento text,
  cargo text,
  gestor text,
  status text,
  admissao_excel text,
  fonte_aba text,
  fonte_arquivo text,
  reference_date text,
  imported_at text
)
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if public.mobile_session_owner(p_session_token) is null then
    raise exception using errcode = 'P0001', message = 'Sessao mobile invalida ou expirada.';
  end if;

  return query
  select
    collaborator.matricula,
    collaborator.nome,
    collaborator.departamento,
    collaborator.cargo,
    collaborator.gestor,
    collaborator.status,
    collaborator.admissao_excel,
    collaborator.fonte_aba,
    collaborator.fonte_arquivo,
    collaborator.reference_date,
    collaborator.imported_at
  from public.headcount_colaboradores collaborator
  where collaborator.status = 'ATIVO'
    and collaborator.matricula = regexp_replace(coalesce(p_matricula, ''), '[^0-9]', '', 'g')
  limit 1;
end;
$$;

create or replace function public.mobile_inventory_parcels(
  p_session_token text,
  p_farm_name text
)
returns table (
  id uuid,
  nome_fazenda text,
  parcela text,
  bloco text,
  ano_plantio integer,
  cultivar text,
  area_ha numeric,
  plantas integer
)
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if public.mobile_session_owner(p_session_token) is null then
    raise exception using errcode = 'P0001', message = 'Sessao mobile invalida ou expirada.';
  end if;

  return query
  select inventory.id, inventory.nome_fazenda, inventory.parcela, inventory.bloco,
    inventory.ano_plantio, inventory.cultivar, inventory.area_ha, inventory.plantas
  from public.inventario_parcelas inventory
  where inventory.ativo = true
    and upper(trim(inventory.nome_fazenda)) = upper(trim(coalesce(p_farm_name, '')))
  order by inventory.parcela;
end;
$$;

create or replace function public.mobile_register_device(
  p_session_token text,
  p_device jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_owner text;
  v_device_id text;
begin
  v_owner := public.mobile_session_owner(p_session_token);
  if v_owner is null then
    raise exception using errcode = 'P0001', message = 'Sessao mobile invalida ou expirada.';
  end if;

  v_device_id := nullif(trim(p_device->>'id'), '');
  if v_device_id is null then
    raise exception using errcode = '22023', message = 'Dispositivo invalido.';
  end if;

  insert into public.mobile_dispositivos (
    id,
    usuario_id,
    plataforma,
    modelo,
    fabricante,
    app_version,
    ultimo_sync_em,
    created_at,
    updated_at
  ) values (
    v_device_id,
    v_owner,
    nullif(trim(p_device->>'plataforma'), ''),
    nullif(trim(p_device->>'modelo'), ''),
    nullif(trim(p_device->>'fabricante'), ''),
    nullif(trim(p_device->>'app_version'), ''),
    now(),
    coalesce(nullif(p_device->>'created_at', '')::timestamptz, now()),
    now()
  ) on conflict (id) do update set
    usuario_id = excluded.usuario_id,
    plataforma = excluded.plataforma,
    modelo = excluded.modelo,
    fabricante = excluded.fabricante,
    app_version = excluded.app_version,
    ultimo_sync_em = excluded.ultimo_sync_em,
    updated_at = excluded.updated_at;

  update public.mobile_sessions
  set dispositivo_id = v_device_id, ultimo_uso_em = now()
  where token_hash = encode(digest(coalesce(p_session_token, ''), 'sha256'), 'hex');

  return jsonb_build_object('registered', true, 'device_id', v_device_id);
end;
$$;

create or replace function public.mobile_log_event(
  p_session_token text,
  p_status text,
  p_mensagem text,
  p_resposta_id text default null,
  p_dispositivo_id text default null
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_owner text;
begin
  v_owner := public.mobile_session_owner(p_session_token);
  if v_owner is null then return false; end if;

  insert into public.mobile_audit_log (
    matricula,
    dispositivo_id,
    acao,
    entidade,
    entidade_id,
    detalhes
  ) values (
    v_owner,
    nullif(trim(coalesce(p_dispositivo_id, '')), ''),
    'client_' || left(regexp_replace(lower(coalesce(p_status, 'info')), '[^a-z0-9_]+', '_', 'g'), 40),
    'mobile_respostas',
    nullif(trim(coalesce(p_resposta_id, '')), ''),
    jsonb_build_object('mensagem', left(coalesce(p_mensagem, ''), 1000))
  );
  return true;
end;
$$;

create or replace function public.mobile_sync_bundle(
  p_session_token text,
  p_respostas jsonb default '[]'::jsonb,
  p_gps jsonb default '[]'::jsonb,
  p_anexos jsonb default '[]'::jsonb,
  p_deposits jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_owner text;
  v_device_id text;
  v_response_count integer := 0;
  v_gps_count integer := 0;
  v_attachment_count integer := 0;
  v_deposit_result jsonb := jsonb_build_object('synced', 0, 'skipped', 0);
begin
  v_owner := public.mobile_session_owner(p_session_token);
  if v_owner is null then
    raise exception using errcode = 'P0001', message = 'Sessao mobile invalida ou expirada.';
  end if;

  select dispositivo_id into v_device_id
  from public.mobile_sessions
  where token_hash = encode(digest(coalesce(p_session_token, ''), 'sha256'), 'hex');

  if jsonb_typeof(coalesce(p_respostas, '[]'::jsonb)) <> 'array'
    or jsonb_typeof(coalesce(p_gps, '[]'::jsonb)) <> 'array'
    or jsonb_typeof(coalesce(p_anexos, '[]'::jsonb)) <> 'array'
    or jsonb_typeof(coalesce(p_deposits, '[]'::jsonb)) <> 'array'
    or jsonb_array_length(coalesce(p_respostas, '[]'::jsonb)) > 25
    or jsonb_array_length(coalesce(p_gps, '[]'::jsonb)) > 100
    or jsonb_array_length(coalesce(p_anexos, '[]'::jsonb)) > 50
    or jsonb_array_length(coalesce(p_deposits, '[]'::jsonb)) > 25 then
    raise exception using errcode = '22023', message = 'Lote de sincronizacao invalido ou acima do limite.';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(coalesce(p_respostas, '[]'::jsonb)) item
    where coalesce(nullif(item->>'usuario_id', ''), v_owner) <> v_owner
  ) then
    raise exception using errcode = '42501', message = 'A coleta nao pertence a sessao informada.';
  end if;

  insert into public.mobile_respostas (
    id,
    formulario_id,
    formulario_versao,
    usuario_id,
    dados_json,
    mapeamento_legado,
    status,
    dispositivo_id,
    origem,
    criado_em,
    enviado_em,
    recebido_em,
    atualizado_em,
    updated_at,
    erro_msg,
    tentativas
  )
  select
    row.id,
    row.formulario_id,
    row.formulario_versao,
    v_owner,
    row.dados_json,
    row.mapeamento_legado,
    coalesce(nullif(row.status, ''), 'pendente_validacao'),
    coalesce(nullif(row.dispositivo_id, ''), v_device_id),
    coalesce(nullif(row.origem, ''), 'app_android'),
    coalesce(row.criado_em, now()),
    coalesce(row.enviado_em, now()),
    now(),
    coalesce(row.updated_at, row.criado_em, now()),
    coalesce(row.updated_at, row.criado_em, now()),
    row.erro_msg,
    coalesce(row.tentativas, 0)
  from jsonb_to_recordset(coalesce(p_respostas, '[]'::jsonb)) as row(
    id text,
    formulario_id text,
    formulario_versao integer,
    usuario_id text,
    dados_json jsonb,
    mapeamento_legado jsonb,
    status text,
    dispositivo_id text,
    origem text,
    criado_em timestamptz,
    enviado_em timestamptz,
    updated_at timestamptz,
    erro_msg text,
    tentativas integer
  )
  where row.id is not null
    and row.formulario_id is not null
    and row.dados_json is not null
  on conflict (id) do update set
    formulario_versao = excluded.formulario_versao,
    dados_json = excluded.dados_json,
    mapeamento_legado = excluded.mapeamento_legado,
    status = excluded.status,
    dispositivo_id = excluded.dispositivo_id,
    origem = excluded.origem,
    enviado_em = excluded.enviado_em,
    atualizado_em = excluded.atualizado_em,
    updated_at = excluded.updated_at,
    erro_msg = excluded.erro_msg,
    tentativas = excluded.tentativas
  where excluded.usuario_id = v_owner
    and excluded.updated_at >= coalesce(public.mobile_respostas.updated_at, '-infinity'::timestamptz);

  get diagnostics v_response_count = row_count;

  if exists (
    select 1
    from jsonb_array_elements(coalesce(p_deposits, '[]'::jsonb)) item
    left join public.mobile_respostas response
      on response.id = item->>'source_response_id'
     and response.usuario_id = v_owner
    where nullif(item->>'source_response_id', '') is null
       or response.id is null
  ) then
    raise exception using errcode = '42501', message = 'O despejo nao pertence a uma coleta valida da sessao.';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(coalesce(p_deposits, '[]'::jsonb)) item
    where nullif(trim(item->>'driver_registration'), '') is null
       or nullif(trim(item->>'driver_name'), '') is null
       or nullif(trim(item->>'vehicle_plate'), '') is null
       or nullif(trim(item->>'subproduct'), '') is null
       or nullif(trim(item->>'loading_origin'), '') is null
       or nullif(trim(item->>'scale_ticket_code'), '') is null
       or nullif(trim(item->>'farm'), '') is null
       or nullif(trim(item->>'plot_primary'), '') is null
       or nullif(trim(item->>'deposit_date'), '') is null
       or nullif(trim(item->>'deposit_time'), '') is null
       or nullif(trim(item->>'latitude'), '') is null
       or nullif(trim(item->>'longitude'), '') is null
       or nullif(trim(item->>'dump_photo_storage_path'), '') is null
       or nullif(trim(item->>'dump_photo_latitude'), '') is null
       or nullif(trim(item->>'dump_photo_longitude'), '') is null
       or item->>'dump_photo_storage_path' not like v_owner || '/%'
       or (
         lower(trim(coalesce(item->>'placement_mode', ''))) = 'between_plots'
         and nullif(trim(item->>'plot_secondary'), '') is null
       )
  ) then
    raise exception using errcode = '22023', message = 'Coleta obrigatoria incompleta ou foto sem autoria valida.';
  end if;

  insert into public.mobile_gps (
    id,
    resposta_id,
    campo_id,
    latitude,
    longitude,
    precisao,
    altitude,
    capturado_em
  )
  select
    row.id,
    row.resposta_id,
    row.campo_id,
    row.latitude,
    row.longitude,
    row.precisao,
    row.altitude,
    coalesce(row.capturado_em, now())
  from jsonb_to_recordset(coalesce(p_gps, '[]'::jsonb)) as row(
    id text,
    resposta_id text,
    campo_id text,
    latitude double precision,
    longitude double precision,
    precisao double precision,
    altitude double precision,
    capturado_em timestamptz
  )
  join public.mobile_respostas response
    on response.id = row.resposta_id
   and response.usuario_id = v_owner
  where row.id is not null and row.campo_id is not null
  on conflict (id) do update set
    latitude = excluded.latitude,
    longitude = excluded.longitude,
    precisao = excluded.precisao,
    altitude = excluded.altitude,
    capturado_em = excluded.capturado_em;

  get diagnostics v_gps_count = row_count;

  insert into public.mobile_anexos (
    id,
    resposta_id,
    campo_id,
    storage_path,
    nome_arquivo,
    tamanho_bytes,
    tipo_mime,
    criado_em
  )
  select
    row.id,
    row.resposta_id,
    row.campo_id,
    row.storage_path,
    row.nome_arquivo,
    row.tamanho_bytes,
    row.tipo_mime,
    coalesce(row.criado_em, now())
  from jsonb_to_recordset(coalesce(p_anexos, '[]'::jsonb)) as row(
    id text,
    resposta_id text,
    campo_id text,
    storage_path text,
    nome_arquivo text,
    tamanho_bytes bigint,
    tipo_mime text,
    criado_em timestamptz
  )
  join public.mobile_respostas response
    on response.id = row.resposta_id
   and response.usuario_id = v_owner
  where row.id is not null
    and row.campo_id is not null
    and row.storage_path like v_owner || '/%'
  on conflict (id) do update set
    storage_path = excluded.storage_path,
    nome_arquivo = excluded.nome_arquivo,
    tamanho_bytes = excluded.tamanho_bytes,
    tipo_mime = excluded.tipo_mime,
    criado_em = excluded.criado_em;

  get diagnostics v_attachment_count = row_count;

  if jsonb_array_length(coalesce(p_deposits, '[]'::jsonb)) > 0 then
    v_deposit_result := public.mobile_sync_subproduct_deposits(p_deposits);
  end if;

  update public.mobile_sessions
  set ultimo_uso_em = now()
  where token_hash = encode(digest(coalesce(p_session_token, ''), 'sha256'), 'hex');

  insert into public.mobile_audit_log (
    matricula,
    dispositivo_id,
    acao,
    entidade,
    detalhes
  ) values (
    v_owner,
    v_device_id,
    'sync_bundle',
    'mobile_respostas',
    jsonb_build_object(
      'responses', v_response_count,
      'gps', v_gps_count,
      'attachments', v_attachment_count,
      'deposits', coalesce((v_deposit_result->>'synced')::integer, 0)
    )
  );

  return jsonb_build_object(
    'responses', v_response_count,
    'gps', v_gps_count,
    'attachments', v_attachment_count,
    'deposits', coalesce((v_deposit_result->>'synced')::integer, 0),
    'deposit_result', v_deposit_result
  );
end;
$$;

create or replace function public.mobile_user_responses(
  p_session_token text,
  p_limit integer default 300
)
returns table (
  id text,
  formulario_id text,
  formulario_versao integer,
  usuario_id text,
  dados_json jsonb,
  mapeamento_legado jsonb,
  status text,
  dispositivo_id text,
  criado_em timestamptz,
  enviado_em timestamptz,
  recebido_em timestamptz,
  updated_at timestamptz,
  erro_msg text,
  tentativas integer
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_owner text;
begin
  v_owner := public.mobile_session_owner(p_session_token);
  if v_owner is null then
    raise exception using errcode = 'P0001', message = 'Sessao mobile invalida ou expirada.';
  end if;

  return query
  select
    response.id,
    response.formulario_id,
    response.formulario_versao,
    response.usuario_id,
    response.dados_json,
    response.mapeamento_legado,
    response.status,
    response.dispositivo_id,
    response.criado_em,
    response.enviado_em,
    response.recebido_em,
    response.updated_at,
    response.erro_msg,
    response.tentativas
  from public.mobile_respostas response
  where response.usuario_id = v_owner
    and response.status <> 'excluido'
  order by response.criado_em desc
  limit least(greatest(coalesce(p_limit, 300), 1), 1000);
end;
$$;

create or replace function public.mobile_response_gps(
  p_session_token text,
  p_response_ids text[]
)
returns table (
  id text,
  resposta_id text,
  campo_id text,
  latitude double precision,
  longitude double precision,
  precisao double precision,
  altitude double precision,
  capturado_em timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_owner text;
begin
  v_owner := public.mobile_session_owner(p_session_token);
  if v_owner is null then
    raise exception using errcode = 'P0001', message = 'Sessao mobile invalida ou expirada.';
  end if;

  return query
  select gps.id, gps.resposta_id, gps.campo_id, gps.latitude, gps.longitude,
    gps.precisao, gps.altitude, gps.capturado_em
  from public.mobile_gps gps
  join public.mobile_respostas response on response.id = gps.resposta_id
  where response.usuario_id = v_owner
    and gps.resposta_id = any(coalesce(p_response_ids, array[]::text[]));
end;
$$;

create or replace function public.mobile_response_attachments(
  p_session_token text,
  p_response_ids text[]
)
returns table (
  id text,
  resposta_id text,
  campo_id text,
  storage_path text,
  nome_arquivo text,
  tamanho_bytes bigint,
  tipo_mime text,
  criado_em timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_owner text;
begin
  v_owner := public.mobile_session_owner(p_session_token);
  if v_owner is null then
    raise exception using errcode = 'P0001', message = 'Sessao mobile invalida ou expirada.';
  end if;

  return query
  select attachment.id, attachment.resposta_id, attachment.campo_id,
    attachment.storage_path, attachment.nome_arquivo, attachment.tamanho_bytes,
    attachment.tipo_mime, attachment.criado_em
  from public.mobile_anexos attachment
  join public.mobile_respostas response on response.id = attachment.resposta_id
  where response.usuario_id = v_owner
    and attachment.resposta_id = any(coalesce(p_response_ids, array[]::text[]));
end;
$$;

create or replace function public.audit_field_deposit_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_actor text;
begin
  v_id := case when tg_op = 'DELETE' then old.id else new.id end;
  v_actor := coalesce(
    nullif(current_setting('app.actor_label', true), ''),
    case when tg_op = 'DELETE' then old.reviewed_by_label else new.reviewed_by_label end,
    nullif(current_setting('request.jwt.claim.sub', true), ''),
    'sistema'
  );
  insert into public.field_deposit_audit (
    field_deposit_id,
    acao,
    actor_label,
    old_data,
    new_data
  ) values (
    v_id,
    lower(tg_op),
    v_actor,
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) - 'dump_photo_data_url' else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) - 'dump_photo_data_url' else null end
  );

  return coalesce(new, old);
end;
$$;

drop trigger if exists field_deposit_audit_trigger on public.field_deposits;
create trigger field_deposit_audit_trigger
after insert or update or delete on public.field_deposits
for each row execute function public.audit_field_deposit_change();

-- Remove todas as policies permissivas das tabelas exclusivas do app mobile.
do $$
declare
  policy_row record;
begin
  for policy_row in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = any(array[
        'mobile_respostas', 'mobile_gps', 'mobile_anexos', 'mobile_usuarios',
        'mobile_dispositivos', 'mobile_sync_logs', 'headcount_colaboradores',
        'mobile_sessions', 'mobile_login_attempts', 'mobile_audit_log',
        'field_deposit_audit', 'field_deposit_tombstones'
      ])
  loop
    execute format('drop policy if exists %I on %I.%I',
      policy_row.policyname, policy_row.schemaname, policy_row.tablename);
  end loop;
end;
$$;

revoke all on public.mobile_respostas from anon, authenticated;
revoke all on public.mobile_gps from anon, authenticated;
revoke all on public.mobile_anexos from anon, authenticated;
revoke all on public.mobile_usuarios from anon, authenticated;
revoke all on public.mobile_dispositivos from anon, authenticated;
revoke all on public.mobile_sync_logs from anon, authenticated;
revoke all on public.headcount_colaboradores from anon, authenticated;
revoke all on public.mobile_sessions from anon, authenticated;
revoke all on public.mobile_login_attempts from anon, authenticated;
revoke all on public.mobile_audit_log from anon, authenticated;
revoke all on public.field_deposit_audit from anon, authenticated;
revoke all on public.field_deposit_tombstones from anon, authenticated;

do $$
begin
  if to_regclass('public.headcount_import_snapshots') is not null then
    execute 'revoke all on public.headcount_import_snapshots from anon, authenticated';
  end if;
end;
$$;

-- O dashboard acessa dados apenas por RPC autenticada por sessao de matricula.
revoke all on public.field_deposits from anon, authenticated;
do $$
begin
  if to_regclass('public.vw_dashboard_subprodutos') is not null then
    execute 'revoke all on public.vw_dashboard_subprodutos from anon, authenticated';
  end if;
end;
$$;

revoke all on function public.mobile_sync_subproduct_deposits(jsonb) from public, anon, authenticated;
grant execute on function public.mobile_sync_subproduct_deposits(jsonb) to service_role;

revoke all on function public.mobile_authenticate(text, text, text) from public;
revoke all on function public.mobile_session_profile(text) from public;
revoke all on function public.mobile_logout(text) from public;
revoke all on function public.mobile_headcount_directory(text, integer, integer) from public;
revoke all on function public.mobile_headcount_lookup(text, text) from public;
revoke all on function public.mobile_inventory_parcels(text, text) from public;
revoke all on function public.mobile_register_device(text, jsonb) from public;
revoke all on function public.mobile_log_event(text, text, text, text, text) from public;
revoke all on function public.mobile_sync_bundle(text, jsonb, jsonb, jsonb, jsonb) from public;
revoke all on function public.mobile_user_responses(text, integer) from public;
revoke all on function public.mobile_response_gps(text, text[]) from public;
revoke all on function public.mobile_response_attachments(text, text[]) from public;

grant execute on function public.mobile_authenticate(text, text, text) to anon, authenticated;
grant execute on function public.mobile_session_profile(text) to anon, authenticated;
grant execute on function public.mobile_logout(text) to anon, authenticated;
grant execute on function public.mobile_headcount_directory(text, integer, integer) to anon, authenticated;
grant execute on function public.mobile_headcount_lookup(text, text) to anon, authenticated;
grant execute on function public.mobile_inventory_parcels(text, text) to anon, authenticated;
grant execute on function public.mobile_register_device(text, jsonb) to anon, authenticated;
grant execute on function public.mobile_log_event(text, text, text, text, text) to anon, authenticated;
grant execute on function public.mobile_sync_bundle(text, jsonb, jsonb, jsonb, jsonb) to anon, authenticated;
grant execute on function public.mobile_user_responses(text, integer) to anon, authenticated;
grant execute on function public.mobile_response_gps(text, text[]) to anon, authenticated;
grant execute on function public.mobile_response_attachments(text, text[]) to anon, authenticated;

revoke all on function public.mobile_session_owner(text) from public, anon, authenticated;
revoke all on function public.audit_field_deposit_change() from public, anon, authenticated;
grant execute on function public.mobile_session_profile(text) to service_role;

-- O bucket continua privado. Upload e assinatura passam pela Edge Function vna-mobile-api.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'mobile-anexos',
  'mobile-anexos',
  false,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "pilot read mobile-anexos" on storage.objects;
drop policy if exists "pilot insert mobile-anexos" on storage.objects;
drop policy if exists "pilot update mobile-anexos" on storage.objects;

delete from public.mobile_sessions where expira_em <= now() or revogado_em is not null;
delete from public.mobile_login_attempts where criado_em < now() - interval '30 days';

commit;

select
  has_table_privilege('anon', 'public.headcount_colaboradores', 'SELECT') as anon_le_headcount,
  has_table_privilege('anon', 'public.mobile_respostas', 'SELECT') as anon_le_respostas,
  has_table_privilege('anon', 'public.mobile_respostas', 'INSERT') as anon_insere_respostas,
  has_function_privilege('anon', 'public.mobile_authenticate(text,text,text)', 'EXECUTE') as login_rpc_disponivel,
  has_function_privilege('anon', 'public.mobile_sync_bundle(text,jsonb,jsonb,jsonb,jsonb)', 'EXECUTE') as sync_rpc_disponivel;
